flowchart LR
    A["Aplikasi Mobile<br>(Flutter - Perpustakaan Kampus)"]
        -->|"HTTP Request<br>(JSON)"|
    B["Backend SI<br>(REST API Perpustakaan)"]

    B -->|"Query / Perubahan Data"|
    C[("Database<br>Perpustakaan")]

    C -->|"Data Hasil Query"|
    B

    B -->|"HTTP Response<br>(JSON)"|
    A
